# GCP Inventory
gcp_project: <GCP_PROJECT_NAME>
gcp_cred_kind: serviceaccount
gcp_cred_file: <GCP_CREDENTIAL_JSON_FILE>
zone: us-east4-c
region: us-east4
machine_type: e2-micro
node_count: 6
image: projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts
ansible_user: apex
# View GCP VMs at: https://console.cloud.google.com/compute/instances
# View GCP VPC IP Addresses at: https://console.cloud.google.com/networking/addresses

### Controller Section (values are there for example, replace with your environment) ###
controller_address: <CONTROLLER_ADDRESS>
apex_binary: https://apex-net.s3.amazonaws.com/apex-amd64-linux
apex_zone_name: zone-hub
apex_zone_prefix: 10.185.0.0/20

### Apex Auth ###
apex_auth_uid: kitteh1
apex_auth_password: floofykittens
apex_oidc_client_id_cli: apex-cli
apex_oidc_url: https://auth.apex.local
apex_api_url: https://api.apex.local
apex_url: https://apex.local
