#
# Changes th deployment to use the latest released builds of the images.
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/limitador
images:
  - name: quay.io/nexodus/apiserver
    newTag: 48640484318ba1cf47ece00a6427b932305da6af
  - name: quay.io/nexodus/envsubst
    newTag: 48640484318ba1cf47ece00a6427b932305da6af
  - name: quay.io/nexodus/frontend
    newTag: 48640484318ba1cf47ece00a6427b932305da6af
  - name: quay.io/nexodus/go-ipam
    newTag: 48640484318ba1cf47ece00a6427b932305da6af
